// admin setting action type.
// designation action type.
export const GET_DESIGNATION = "GET_DESIGNATION";
export const GET_DESIGNATION_SUCCESS = "GET_DESIGNATION_SUCCESS";
export const ADD_DESIGINATION = "ADD_DESIGINATION";
export const ADD_DESIGINATION_SUCCESS = "ADD_DESIGINATION_SUCCESS";
export const UPDATE_DESIGNATION = "UPDATE_DESIGNATION";
export const UPDATE_DESIGNATION_SUCCESS = "UPDATE_DESIGNATION_SUCCESS";
export const DEL_DESIGNATION = "DEL_DESIGNATION";
export const DEL_DESIGNATION_SUCCESS = "DEL_DESIGNATION_SUCCESS";

// asset action type.
export const GET_SELECTED_ASSET = "GET_SELECTED_ASSET";

// Employee action type.
export const GET_EMP_LIST = "GET_EMP_LIST";
export const GET_EMP_LIST_SUCCESS = "GET_EMP_LIST_SUCCESS";
export const ADD_EMP = "ADD_EMP";
export const ADD_EMP_SUCCESS = "ADD_EMP_SUCCESS";
export const GET_SELECT_EMP = "SELECT_EMP";
export const GET_SELECT_EMP_SUCCESS = "SELECT_EMP_SUCCESS";
export const DEL_EMP_CERTIFICATE = "DEL_EMP_CERTIFICATE";
export const DEL_EMP_CERTIFICATE_SUCCESS = "DEL_EMP_CERTIFICATE_SUCCESS";
export const ADD_EMP_SKILL = "ADD_EMP_SKILL";
export const ADD_EMP_SKILL_SUCCESS = "ADD_EMP_SKILL_SUCCESS";

// Projects action type.
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_PROJECT_LIST_SUCCES = "GET_PROJECT_LIST_SUCCES";
export const GET_SELECT_PROJECT = "GET_SELECT_PROJECT";
export const GET_SELECT_PROJECT_SUCCESS = "GET_SELECT_PROJECT_SUCCESS";
export const ADD_PROJECT_LEADER = "ADD_PROJECT_LEADER";
export const ADD_PROJECT_MEMBER = "ADD_PROJECT_MEMBER";

// Task action type.
export const GET_EMP_TASK = "GET_EMP_TASK";
export const GET_EMP_TASK_SUCCESS = "GET_EMP_TASK_SUCCESS";
export const GET_PROJECT_ID_TASK = "GET_PROJECT_ID_TASK";
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const DEL_TASK = "DEL_TASK";
export const DEL_TASK_SUCCESS = "DEL_TASK_SUCCESS";
export const ON_CHANGE_TASK_DATE = "ON_CHANGE_TASK_DATE";
export const ADD_PROJECT_FROM_TASK = "ADD_PROJECT_FROM_TASK";
