import uuid from "react-uuid";

// -----------Employee List-------------------------
const empList = [
  {
    value: {
      empId: 29,
      empType: "",
      empName: "Waston",
      doj: "2020-04-01",
      dob: "1995-09-28",
      adharNo: "7877-1212-3343-2121",
      panNo: "ijw77818sw",
      esiNo: "esi10101",
      epfUan: "none",
      qualification: "PHD",
      designation: "Associate Software Engineer",
      gaurdianName: "Vasudevan",
      address: "Vyshagam (H)",
      mobileNo: "8129340696",
      alternativeNo: "9605455550",
      niraMailId: "vimalm@nirasystms.com",
      alternativeMailId: "vimalvyshagam@gmail.com",
      ifscCode: "fdrl0001577",
      bankAccNo: "15770100065383",
      bloodGroup: "B-",
      department: "software Development",
      skill: "Reactjs, Nodejs, Php",
      officeLocation: "trivandrum",
      workPrimise: "home",
      profileImg: "avatar-01.jpg",
    },
    label: "Waston",
  },
  {
    value: {
      empId: 13,
      empType: "",
      empName: "Dutch",
      doj: "2020-04-01",
      dob: "1995-09-28",
      adharNo: "7877-1212-3343-2121",
      panNo: "ijw77818sw",
      esiNo: "esi10101",
      epfUan: "none",
      qualification: "PHD",
      designation: "Associate Software Engineer",
      gaurdianName: "Vasudevan",
      address: "Vyshagam (H)",
      mobileNo: "8129340696",
      alternativeNo: "9605455550",
      niraMailId: "vimalm@nirasystms.com",
      alternativeMailId: "vimalvyshagam@gmail.com",
      ifscCode: "fdrl0001577",
      bankAccNo: "15770100065383",
      bloodGroup: "B-",
      department: "software Development",
      skill: "Reactjs, Nodejs, Php",
      officeLocation: "trivandrum",
      workPrimise: "home",
      profileImg: "nible.png",
    },
    label: "Dutch",
  },
  {
    value: {
      empId: 33,
      empType: "",
      empName: "Jerry",
      doj: "2020-04-01",
      dob: "1995-09-28",
      adharNo: "7877-1212-3343-2121",
      panNo: "ijw77818sw",
      esiNo: "esi10101",
      epfUan: "none",
      qualification: "PHD",
      designation: "Associate Software Engineer",
      gaurdianName: "Vasudevan",
      address: "Vyshagam (H)",
      mobileNo: "8129340696",
      alternativeNo: "9605455550",
      niraMailId: "vimalm@nirasystms.com",
      alternativeMailId: "vimalvyshagam@gmail.com",
      ifscCode: "fdrl0001577",
      bankAccNo: "15770100065383",
      bloodGroup: "B-",
      department: "software Development",
      skill: "Reactjs, Nodejs, Php",
      officeLocation: "trivandrum",
      workPrimise: "home",
      profileImg: "avatar-06.png",
    },
    label: "Jerry",
  },
  {
    value: {
      empId: 100,
      empType: "",
      empName: "Tom",
      doj: "2020-04-01",
      dob: "1995-09-28",
      adharNo: "7877-1212-3343-2121",
      panNo: "ijw77818sw",
      esiNo: "esi10101",
      epfUan: "none",
      qualification: "PHD",
      designation: "Associate Software Engineer",
      gaurdianName: "Vasudevan",
      address: "Vyshagam (H)",
      mobileNo: "8129340696",
      alternativeNo: "9605455550",
      niraMailId: "vimalm@nirasystms.com",
      alternativeMailId: "vimalvyshagam@gmail.com",
      ifscCode: "fdrl0001577",
      bankAccNo: "15770100065383",
      bloodGroup: "B-",
      department: "software Development",
      skill: "Reactjs, Nodejs, Php",
      officeLocation: "trivandrum",
      workPrimise: "home",
      profileImg: "avatar-07.jpg",
    },
    label: "Tom",
  },
  {
    value: {
      empId: 66,
      empType: "",
      empName: "Spike",
      doj: "2020-04-01",
      dob: "1995-09-28",
      adharNo: "7877-1212-3343-2121",
      panNo: "ijw77818sw",
      esiNo: "esi10101",
      epfUan: "none",
      qualification: "PHD",
      designation: "Associate Software Engineer",
      gaurdianName: "Vasudevan",
      address: "Vyshagam (H)",
      mobileNo: "8129340696",
      alternativeNo: "9605455550",
      niraMailId: "vimalm@nirasystms.com",
      alternativeMailId: "vimalvyshagam@gmail.com",
      ifscCode: "fdrl0001577",
      bankAccNo: "15770100065383",
      bloodGroup: "B-",
      department: "software Development",
      skill: "Reactjs, Nodejs, Php",
      officeLocation: "trivandrum",
      workPrimise: "home",
      profileImg: "avatar-05.jpeg",
    },
    label: "Spike",
  },
];

// ---------------Certificates ---------------------
const empCertificates = [
  {
    empId: "29",
    certificate: [
      { certificateName: "React master in Redux", date: "2002-02-09" },
      { certificateName: "Dot net core V3", date: "2002-02-09" },
      { certificateName: "RxJs", date: "2002-02-09" },
      { certificateName: "Angular", date: "2002-02-09" },
    ],
  },
  {
    empId: "13",
    certificate: [
      { certificateName: "React master in Redux", date: "2002-02-09" },
      { certificateName: "RxJs", date: "2002-02-09" },
    ],
  },
  {
    empId: "33",
    certificate: [
      { certificateName: "React master in Redux", date: "2002-02-09" },
      { certificateName: "RxJs", date: "2002-02-09" },
    ],
  },
  {
    empId: "66",
    certificate: [
      { certificateName: "React master in Redux", date: "2002-02-09" },
      { certificateName: "RxJs", date: "2002-02-09" },
    ],
  },
];

// ------------------ Skill ----------------------
const empSkills = [
  {
    empId: "29",
    skill: [
      {
        skillId: 1,
        skillCategory: "technologies",
        skillName: [".NET TECHNOLOGIES", "MEAR", "MEAN", "Odoo"],
      },
      {
        skillId: 2,
        skillCategory: "web based language",
        skillName: ["ASP.NET", "APS.NET MVC", "Angular 5", "jQuery"],
      },
      {
        skillId: 3,
        skillCategory: "desktop based language",
        skillName: ["C#.NET", "VB.NET", "Scala", "Spark"],
      },
    ],
  },
];
export { empList, empCertificates, empSkills };
