export const payRollItem = {
  addition: [
    {
      additionName: "Leave",
      additionCategory: "monthly renumeration",
      defaultUnitAmount: "1000",
    },
    {
      additionName: "Arrears of salary",
      additionCategory: "additional renumeration",
      defaultUnitAmount: "1200",
    },
    {
      additionName: "Gratuity	",
      additionCategory: "monthly renumeration",
      defaultUnitAmount: "7000",
    },
  ],
};

export const salaryReport = [
  {
    empId: 29,
    empType: "",
    empName: "Waston",
    designation: "Associate Software Engineer",
    profileImg: "avatar-01.jpg",
    fromDate: new Date("6-02-2013"),
    toDate: new Date("6-02-2014"),
  },
  {
    empId: 13,
    empType: "",
    empName: "Dutch",
    designation: "Associate Software Engineer",
    profileImg: "nible.png",
    fromDate: new Date("7-02-2013"),
    toDate: new Date("7-02-2014"),
  },
  {
    empId: 33,
    empType: "",
    empName: "Jerry",
    designation: "Associate Software Engineer",
    profileImg: "avatar-06.png",
    fromDate: new Date("9-02-2013"),
    toDate: new Date("9-02-2014"),
  },
  {
    empId: 100,
    empType: "",
    empName: "Tom",
    designation: "Associate Software Engineer",
    profileImg: "avatar-07.jpg",
    fromDate: new Date("10-02-2013"),
    toDate: new Date("10-02-2014"),
  },
  {
    empId: 66,
    empType: "",
    empName: "Spike",
    designation: "Associate Software Engineer",
    profileImg: "avatar-05.jpeg",
    fromDate: new Date("10-01-2012"),
    toDate: new Date("10-01-2013"),
  },
];

export const employeePlList = [
  {
    empId: 29,
    empType: "",
    empName: "Waston",
    designation: "Associate Software Engineer",
    profileImg: "avatar-01.jpg",
    fromDate: new Date("6-02-2013"),
    toDate: new Date("6-02-2014"),
    pLSlpitUp: [
      {
        date: new Date("10-2-2016"),
        amountDebited: 0,
        amountEncashed: 1775,
        outstandingAmount: 0,
      },
      {
        date: new Date("12-2-2016"),
        amountDebited: 500,
        amountEncashed: 0,
        outstandingAmount: 1275,
      },
      {
        date: new Date("10-3-2016"),
        amountDebited: 0,
        amountEncashed: 500,
        outstandingAmount: 1275,
      },
      {
        date: new Date("28-3-2016"),
        amountDebited: 2000,
        amountEncashed: 400,
        outstandingAmount: 2875,
      },
      {
        date: new Date("1-5-2016"),
        amountDebited: 2825,
        amountEncashed: 200,
        outstandingAmount: 6000,
      },
    ],
  },
  {
    empId: 13,
    empType: "",
    empName: "Dutch",
    designation: "Associate Software Engineer",
    profileImg: "nible.png",
    fromDate: new Date("7-02-2013"),
    toDate: new Date("7-02-2014"),
    pLSlpitUp: [
      {
        date: new Date("10-2-2016"),
        amountDebited: 2100,
        amountEncashed: 0,
        outstandingAmount: -2100,
      },
      {
        date: new Date("12-2-2016"),
        amountDebited: 0,
        amountEncashed: 4000,
        outstandingAmount: 1900,
      },
      {
        date: new Date("10-3-2016"),
        amountDebited: 0,
        amountEncashed: 2200,
        outstandingAmount: 6200,
      },
      {
        date: new Date("28-3-2016"),
        amountDebited: 0,
        amountEncashed: 1900,
        outstandingAmount: 8100,
      },
    ],
  },
  {
    empId: 33,
    empType: "",
    empName: "Jerry",
    designation: "Associate Software Engineer",
    profileImg: "avatar-06.png",
    fromDate: new Date("9-02-2013"),
    toDate: new Date("9-02-2014"),
    pLSlpitUp: [
      {
        date: new Date("10-2-2016"),
        amountDebited: 600,
        amountEncashed: 0,
        outstandingAmount: 600,
      },
      {
        date: new Date("12-2-2016"),
        amountDebited: 5000,
        amountEncashed: 0,
        outstandingAmount: 5600,
      },
      {
        date: new Date("10-3-2016"),
        amountDebited: 0,
        amountEncashed: 100,
        outstandingAmount: 5500,
      },
      {
        date: new Date("28-3-2016"),
        amountDebited: 2900,
        amountEncashed: 0,
        outstandingAmount: 2600,
      },
    ],
  },
  {
    empId: 100,
    empType: "",
    empName: "Tom",
    designation: "Associate Software Engineer",
    profileImg: "avatar-07.jpg",
    fromDate: new Date("10-02-2013"),
    toDate: new Date("10-02-2014"),
    pLSlpitUp: [
      {
        date: new Date("10-2-2016"),
        amountDebited: 220,
        amountEncashed: 0,
        outstandingAmount: -220,
      },
      {
        date: new Date("12-2-2016"),
        amountDebited: 0,
        amountEncashed: 560,
        outstandingAmount: 340,
      },
      {
        date: new Date("10-3-2016"),
        amountDebited: 0,
        amountEncashed: 4000,
        outstandingAmount: 4340,
      },
      {
        date: new Date("28-3-2016"),
        amountDebited: 0,
        amountEncashed: 4440,
        outstandingAmount: 8780,
      },
    ],
  },
  {
    empId: 66,
    empType: "",
    empName: "Spike",
    designation: "Associate Software Engineer",
    profileImg: "avatar-05.jpeg",
    fromDate: new Date("10-01-2012"),
    toDate: new Date("10-01-2013"),
    pLSlpitUp: [
      {
        date: new Date("10-2-2016"),
        amountDebited: 220,
        amountEncashed: 0,
        outstandingAmount: -220,
      },
      {
        date: new Date("12-2-2016"),
        amountDebited: 0,
        amountEncashed: 6100,
        outstandingAmount: 6100,
      },
      {
        date: new Date("10-3-2016"),
        amountDebited: 750,
        amountEncashed: 0,
        outstandingAmount: 5350,
      },
      {
        date: new Date("28-3-2016"),
        amountDebited: 0,
        amountEncashed: 250,
        outstandingAmount: 5100,
      },
      {
        date: new Date("28-3-2016"),
        amountDebited: 0,
        amountEncashed: 700,
        outstandingAmount: 4400,
      },
    ],
  },
];
