const tasks = [
  {
    projectId: 1,
    projectName: "Employee Managment",
    empId: 29,
    empName: "Waston",
    taskId: 1,
    taskTitle: "Dev project listing view  ",
    createdBy: "Waston",
    createdDate: "05-19-2020",
    hourSpent: "12",
    hourBillable: "8",
    status: "inProgress",
    description:
      "User interface design or user interface engineering is the design of user interfaces for machines and software, such as computers, home appliances, mobile devices, and other electronic devices, with the focus on maximizing usability and the user experience. ",
  },
  {
    projectId: 1,
    projectName: "Employee Managment",
    empId: 29,
    empName: "Waston",
    taskId: 2,
    taskTitle: "Dev UI home view ",
    createdBy: "Waston",
    createdDate: "05-11-2020",
    hourSpent: "12",
    hourBillable: "8",
    status: "inProgress",
    description:
      "User interface design or user interface engineering is the design of user interfaces for machines and software, such as computers, home appliances, mobile devices, and other electronic devices, with the focus on maximizing usability and the user experience. ",
  },
  {
    projectId: 1,
    projectName: "Employee Managment",
    empId: 29,
    empName: "Waston",
    taskId: 5,
    taskTitle: "Dev UI store view ",
    createdBy: "Waston",
    createdDate: "05-11-2020",
    hourSpent: "12",
    hourBillable: "8",
    status: "inProgress",
    description:
      "User interface design or user interface engineering is the design of user interfaces for machines and software, such as computers, home appliances, mobile devices, and other electronic devices, with the focus on maximizing usability and the user experience. ",
  },
  {
    projectId: 2,
    projectName: "Marriot Resturent management",
    empId: 29,
    empName: "Waston",
    taskId: 3,
    taskTitle: "Dev side-bar and header",
    createdBy: "Waston",
    createdDate: "05-18-2020",
    hourSpent: "12",
    hourBillable: "8",
    status: "completed",
    description:
      "Renowned for its dynamic handling, XE’s performance has been enhanced even further. With upgrades to the suspension and revised JaguarDrive Control, be prepared for a thrilling ride.",
  },
  {
    projectId: 2,
    projectName: "Marriot Resturent management",
    empId: 30,
    empName: "Waston",
    taskId: 4,
    taskTitle: "Dev side-bar and header",
    createdBy: "Waston",
    createdDate: "05-10-2020",
    hourSpent: "12",
    hourBillable: "8",
    status: "completed",
    description:
      "Renowned for its dynamic handling, XE’s performance has been enhanced even further. With upgrades to the suspension and revised JaguarDrive Control, be prepared for a thrilling ride.",
  },
];
export { tasks };
